apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
    - name: nginx
      image: nginx
      env:
       - name: course
         value: "devOps"
       - name: trainer
         value: "sivakumar reddy"
       - name: duration
         value: "12ohrs"