apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    - name: nginx
      image: nginx
      resouces:
        requests:
          cpu: 100m
          memory: 68mi
        limis:
          cpu: 120m
          memory: 100mi
           