apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: duration
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: trainer