apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespaces: expense
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
             name: nginx-secret