apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
   - name: nginx-svc-port
     protocol: TCP
     port: 80 # this is service port
     targetPort: 80 # this is container port
