apiVersion: v1
kind: Service
metadata:
   name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80 # it is service port
      targetPort: 80 # it is container port in a pod