apiVersion: v1
kind: Service
metadata:
  name: sevice-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
   - name: nginx-svc-ports
     protocol: TCP
     port: 80 #it is service port
     targetPort: 80 # it is container port