apiVersion: v1
kind: Pod
metadata:
  name: all
  labels:
    project: expense
    environment: dev
    module: backend
  annotations:
    imageregistry: "https://www.github.com"
spec:
  containers:
    - name: nginx
      image: nginx
    - name: node
      image: lts-bookworm-slim
      env:
        - name: course
          value: "devOps"
        - name: duration
          value: "120h"
        - name: trainer
          value: "sivakumar"
      resources:
        requests:
          cpu: 100m
          memory: 68Mi
        limits:
          cpu: 120m
          memory: 100Mi
