FROM almalinux:9
ENV author="siva" \
      company="join" \
      topic="docker" \
      duration="40hours" 
RUN echo "course:${author}", "duration:${duration}"
# CMD ["nginx", "-g", "daemon off;"]
# CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]
CMD ["google.com"]
ENTRYPOINT ["ping"]
LABEL author="siva" \
      company="join" \
      topic="docker" \
      duration="40hours" 
