FROM almalinux:9
RUN dnf install nginx -y
# CMD ["nginx", "-g", "daemon off;"]
CMD ["ping", "google.com"]
LABEL author="siva" \
      company="join" \
      topic="docker" \
      duration="40hours" \
